// GENERATED by the avatar art script. Coordinates are in a 200 x 240 box.

// ignore_for_file: prefer_single_quotes, lines_longer_than_80_chars



class AP {

  const AP(this.d, this.fill, {this.stroke, this.sw = 0, this.op = 1});

  final String d;

  final String fill;

  final String? stroke;

  final double sw;

  final double op;

}



class AT {

  const AT(this.text, this.x, this.y, this.size, this.fill, this.font);

  final String text;

  final double x;

  final double y;

  final double size;

  final String fill;

  final String font;

}



class APose {

  const APose({this.eyes, required this.mouth, this.brows, this.extra = const [], this.texts = const []});

  final String? eyes;

  final String mouth;

  final String? brows;

  final List<AP> extra;

  final List<AT> texts;

}



const List<AP> avatarNeck = [AP('M86 132 L114 132 L116 176 C106 182 94 182 84 176 Z', 'skinShade')];

const List<AP> avatarEars = [AP('M35 104 A9 14 0 1 0 53 104 A9 14 0 1 0 35 104 Z', 'skin'), AP('M147 104 A9 14 0 1 0 165 104 A9 14 0 1 0 147 104 Z', 'skin'), AP('M41 104 A4 7 0 1 0 49 104 A4 7 0 1 0 41 104 Z', 'skinShade'), AP('M151 104 A4 7 0 1 0 159 104 A4 7 0 1 0 151 104 Z', 'skinShade')];

const List<AP> avatarBlush = [AP('M60 122 A8 8 0 1 0 76 122 A8 8 0 1 0 60 122 Z', 'blush', op: 0.45), AP('M124 122 A8 8 0 1 0 140 122 A8 8 0 1 0 124 122 Z', 'blush', op: 0.45)];

const Map<String, List<AP>> avatarBodies = {
  'tee': [AP('M34 240 C34 196 58 176 86 172 L114 172 C142 176 166 196 166 240 Z', 'outfit'), AP('M86 172 C90 184 110 184 114 172 Z', 'skin')],
  'hoodie': [AP('M30 240 C30 194 56 172 84 168 L116 168 C144 172 170 194 170 240 Z', 'outfit'), AP('M72 172 C78 196 122 196 128 172 C118 178 82 178 72 172 Z', 'outfitShade'), AP('M92 190 L90 214 M108 190 L110 214', 'none', stroke: 'outfitShade', sw: 3)],
  'shirt': [AP('M34 240 C34 196 58 176 86 172 L114 172 C142 176 166 196 166 240 Z', 'outfit'), AP('M86 172 L100 196 L114 172 Z', 'skin'), AP('M86 170 L100 196 L76 190 Z M114 170 L100 196 L124 190 Z', '#FFFFFF'), AP('M100 198 L100 240', 'none', stroke: 'outfitShade', sw: 2.5), AP('M97.8 212 A2.2 2.2 0 1 0 102.2 212 A2.2 2.2 0 1 0 97.8 212 Z', 'outfitShade'), AP('M97.8 228 A2.2 2.2 0 1 0 102.2 228 A2.2 2.2 0 1 0 97.8 228 Z', 'outfitShade')],
  'turtleneck': [AP('M34 240 C34 196 58 176 86 172 L114 172 C142 176 166 196 166 240 Z', 'outfit'), AP('M84 158 L116 158 L118 182 C106 188 94 188 82 182 Z', 'outfitShade')],
  'jacket': [AP('M34 240 C34 196 58 176 86 172 L114 172 C142 176 166 196 166 240 Z', '#F4F1EE'), AP('M86 172 C90 184 110 184 114 172 Z', 'skin'), AP('M34 240 C34 196 58 176 84 170 L90 186 L96 240 Z', 'outfit'), AP('M166 240 C166 196 142 176 116 170 L110 186 L104 240 Z', 'outfit'), AP('M84 170 L90 186 L80 200 M116 170 L110 186 L120 200', 'none', stroke: 'outfitShade', sw: 3), AP('M60 214 L60 240 M140 214 L140 240', 'none', stroke: 'outfitShade', sw: 2.5)],
  'polo': [AP('M34 240 C34 196 58 176 86 172 L114 172 C142 176 166 196 166 240 Z', 'outfit'), AP('M86 172 C90 180 110 180 114 172 Z', 'skin'), AP('M84 168 L94 188 L100 176 L106 188 L116 168 L108 172 L100 176 L92 172 Z', 'outfitShade'), AP('M100 178 L100 204', 'none', stroke: 'outfitShade', sw: 2.2), AP('M98.2 186 A1.8 1.8 0 1 0 101.8 186 A1.8 1.8 0 1 0 98.2 186 Z', '#FFFFFF'), AP('M98.2 196 A1.8 1.8 0 1 0 101.8 196 A1.8 1.8 0 1 0 98.2 196 Z', '#FFFFFF')],
  'suit': [AP('M34 240 C34 196 58 176 86 172 L114 172 C142 176 166 196 166 240 Z', 'outfit'), AP('M86 172 L100 206 L114 172 Z', '#FFFFFF'), AP('M96 178 L104 178 L107 214 L100 224 L93 214 Z', 'accent'), AP('M86 170 L100 206 L78 188 Z M114 170 L100 206 L122 188 Z', 'outfitShade'), AP('M98 226 A2 2 0 1 0 102 226 A2 2 0 1 0 98 226 Z', 'outfitShade')],
  'kurta': [AP('M36 240 C36 196 60 178 86 172 L114 172 C140 178 164 196 164 240 Z', 'outfit'), AP('M86 172 C90 178 110 178 114 172 L112 166 L88 166 Z', 'outfitShade'), AP('M100 172 L100 210', 'none', stroke: 'outfitShade', sw: 2.4), AP('M98.2 182 A1.8 1.8 0 1 0 101.8 182 A1.8 1.8 0 1 0 98.2 182 Z', 'accent'), AP('M98.2 192 A1.8 1.8 0 1 0 101.8 192 A1.8 1.8 0 1 0 98.2 192 Z', 'accent'), AP('M98.2 202 A1.8 1.8 0 1 0 101.8 202 A1.8 1.8 0 1 0 98.2 202 Z', 'accent')],
  'dress': [AP('M40 240 C42 200 62 184 80 182 L120 182 C138 184 158 200 160 240 Z', 'outfit'), AP('M80 182 L84 170 M120 182 L116 170', 'none', stroke: 'outfit', sw: 5), AP('M80 182 C92 190 108 190 120 182', 'none', stroke: 'outfitShade', sw: 2.5)],
};

const Map<String, List<AP>> avatarHeads = {
  'oval': [AP('M100 32 C136 32 158 60 158 96 C158 136 132 162 100 162 C68 162 42 136 42 96 C42 60 64 32 100 32 Z', 'skin')],
  'round': [AP('M100 34 C140 34 162 62 162 100 C162 138 136 160 100 160 C64 160 38 138 38 100 C38 62 60 34 100 34 Z', 'skin')],
  'square': [AP('M100 34 C140 34 158 56 158 92 L156 124 C152 148 128 162 100 162 C72 162 48 148 44 124 L42 92 C42 56 60 34 100 34 Z', 'skin')],
  'heart': [AP('M100 34 C138 34 160 58 158 94 C156 126 132 160 100 164 C68 160 44 126 42 94 C40 58 62 34 100 34 Z', 'skin')],
  'jaw': [AP('M100 34 C140 34 158 58 158 92 L156 120 C154 140 138 156 118 163 L82 163 C62 156 46 140 44 120 L42 92 C42 58 60 34 100 34 Z', 'skin')],
};

const Map<String, List<AP>> avatarHairBack = {
  'long': [AP('M42 88 C36 40 68 24 100 24 C134 24 166 40 158 90 L164 196 C142 208 58 208 36 196 Z', 'hair')],
  'wavy': [AP('M40 90 C34 40 68 24 100 24 C134 24 168 40 160 90 C170 120 156 140 168 168 C176 190 150 206 128 198 L72 198 C50 206 24 190 32 168 C44 140 30 120 40 90 Z', 'hair')],
  'bob': [AP('M40 92 C36 42 68 26 100 26 C134 26 166 42 160 92 L162 148 C150 158 136 156 130 150 L70 150 C64 156 50 158 38 148 Z', 'hair')],
  'ponytail': [AP('M134 46 C176 44 184 104 170 150 C166 170 150 176 148 160 C160 120 156 76 128 58 Z', 'hair')],
  'bun': [AP('M76 30 A24 24 0 1 0 124 30 A24 24 0 1 0 76 30 Z', 'hair'), AP('M84 30 C90 20 110 20 116 30', 'none', stroke: 'hairShade', sw: 3)],
  'braids': [AP('M44 96 L40 190 C40 204 60 204 60 190 L62 110 Z', 'hair'), AP('M156 96 L160 190 C160 204 140 204 140 190 L138 110 Z', 'hair'), AP('M42 130 L60 134 M42 150 L60 154 M42 170 L60 174 M158 130 L140 134 M158 150 L140 154 M158 170 L140 174', 'none', stroke: 'hairShade', sw: 3)],
  'manbun': [AP('M85 26 A15 15 0 1 0 115 26 A15 15 0 1 0 85 26 Z', 'hair'), AP('M90 26 C94 18 106 18 110 26', 'none', stroke: 'hairShade', sw: 2.5)],
  'afro': [AP('M100 8 C150 8 184 40 180 90 C186 130 160 150 150 140 L50 140 C40 150 14 130 20 90 C16 40 50 8 100 8 Z', 'hair')],
  'hijab': [AP('M100 22 C146 22 172 56 170 104 C168 150 160 176 176 204 L24 204 C40 176 32 150 30 104 C28 56 54 22 100 22 Z', 'hair'), AP('M30 204 C60 190 140 190 170 204 L172 240 L28 240 Z', 'hair')],
};

const Map<String, List<AP>> avatarHairFront = {
  'short': [AP('M44 98 C38 50 66 28 100 28 C136 28 164 48 156 98 C152 76 140 62 124 58 C110 72 80 74 62 66 C52 76 46 86 44 98 Z', 'hair')],
  'buzz': [AP('M46 90 C44 50 70 32 100 32 C132 32 156 50 154 90 C140 70 122 62 100 62 C78 62 60 70 46 90 Z', 'hair', op: 0.9)],
  'sidepart': [AP('M42 102 C34 48 66 26 102 26 C138 26 166 50 158 100 C156 78 146 62 132 56 C120 50 96 48 74 64 C60 74 50 86 42 102 Z', 'hair'), AP('M74 64 C92 50 116 48 132 56', 'none', stroke: 'hairShade', sw: 3)],
  'curly': [AP('M52 78 m-15 0 a15 15 0 1 0 30 0 a15 15 0 1 0 -30 0 M62 56 m-15 0 a15 15 0 1 0 30 0 a15 15 0 1 0 -30 0 M82 42 m-15 0 a15 15 0 1 0 30 0 a15 15 0 1 0 -30 0 M104 38 m-15 0 a15 15 0 1 0 30 0 a15 15 0 1 0 -30 0 M126 44 m-15 0 a15 15 0 1 0 30 0 a15 15 0 1 0 -30 0 M144 58 m-15 0 a15 15 0 1 0 30 0 a15 15 0 1 0 -30 0 M152 80 m-15 0 a15 15 0 1 0 30 0 a15 15 0 1 0 -30 0 M72 64 m-15 0 a15 15 0 1 0 30 0 a15 15 0 1 0 -30 0 M94 56 m-15 0 a15 15 0 1 0 30 0 a15 15 0 1 0 -30 0 M116 58 m-15 0 a15 15 0 1 0 30 0 a15 15 0 1 0 -30 0 M134 70 m-15 0 a15 15 0 1 0 30 0 a15 15 0 1 0 -30 0 ', 'hair')],
  'long': [AP('M42 110 C36 50 66 26 100 26 C136 26 164 50 158 110 C152 80 132 60 110 56 C104 70 84 82 58 84 C50 92 46 100 42 110 Z', 'hair')],
  'wavy': [AP('M42 108 C36 50 66 26 100 26 C136 26 164 50 158 108 C150 80 136 64 116 60 C112 74 96 80 82 74 C70 84 54 90 42 108 Z', 'hair')],
  'bob': [AP('M42 104 C36 50 66 28 100 28 C136 28 164 50 158 104 C150 84 142 74 132 70 L68 70 C58 74 50 84 42 104 Z', 'hair'), AP('M68 70 L132 70', 'none', stroke: 'hairShade', sw: 2)],
  'ponytail': [AP('M44 96 C40 50 68 30 100 30 C134 30 160 50 156 96 C150 70 128 56 100 56 C74 56 52 70 44 96 Z', 'hair')],
  'bun': [AP('M44 96 C40 50 68 32 100 32 C134 32 160 50 156 96 C150 70 128 58 100 58 C74 58 52 70 44 96 Z', 'hair')],
  'braids': [AP('M44 96 C40 50 68 30 100 30 C134 30 160 50 156 96 C146 72 124 60 100 60 C78 60 56 70 44 96 Z', 'hair'), AP('M100 32 L100 60', 'none', stroke: 'hairShade', sw: 2.5)],
  'afro': [AP('M40 92 C44 72 58 60 100 58 C142 60 156 72 160 92 C168 60 150 30 100 30 C50 30 32 60 40 92 Z', 'hair')],
  'bald': [],
  'quiff': [AP('M44 96 C38 56 60 30 90 24 C104 12 132 10 146 22 C156 32 150 42 142 44 C154 56 158 76 156 96 C152 74 140 62 124 58 C104 52 80 56 62 66 C52 74 46 84 44 96 Z', 'hair'), AP('M96 26 C112 18 132 18 142 28', 'none', stroke: 'hairShade', sw: 2.5)],
  'spiky': [AP('M44 96 C42 72 46 54 54 44 L54 24 L68 36 L76 14 L88 32 L100 10 L110 30 L124 14 L128 34 L146 24 L144 44 C154 58 158 76 156 96 C150 72 132 60 100 60 C72 60 52 72 44 96 Z', 'hair')],
  'fade': [AP('M50 80 C48 46 72 30 100 30 C128 30 152 46 150 80 C138 64 120 58 100 58 C80 58 62 64 50 80 Z', 'hair'), AP('M44 104 C42 90 46 80 52 74 L56 92 Z M156 104 C158 90 154 80 148 74 L144 92 Z', 'hair', op: 0.45)],
  'slick': [AP('M44 94 C40 50 68 28 100 28 C134 28 160 50 156 94 C152 70 142 58 128 54 C112 48 88 48 72 54 C58 58 48 70 44 94 Z', 'hair'), AP('M72 40 C90 34 112 34 130 40 M66 48 C86 42 116 42 136 48', 'none', stroke: 'hairShade', sw: 2.2)],
  'fringe': [AP('M42 100 C36 48 66 26 100 26 C136 26 164 48 158 100 C156 86 150 78 146 76 L136 72 L126 78 L114 72 L100 78 L86 72 L74 78 L62 72 L54 76 C50 78 44 86 42 100 Z', 'hair')],
  'manbun': [AP('M44 96 C40 50 68 32 100 32 C134 32 160 50 156 96 C150 70 128 56 100 56 C74 56 52 70 44 96 Z', 'hair'), AP('M100 34 L100 56', 'none', stroke: 'hairShade', sw: 2)],
  'hijab': [AP('M40 104 C40 56 66 34 100 34 C134 34 160 56 160 104 C158 64 134 48 100 48 C66 48 42 64 40 104 Z', 'hairShade', op: 0.55)],
};

const Map<String, List<AP>> avatarHairFrame = {
  'hijab': [AP('M40 104 C38 150 70 176 100 176 C130 176 162 150 160 104', 'none', stroke: 'hairShade', sw: 3)],
};

const Map<String, List<AP>> avatarEyes = {
  'round': [AP('M69 102 A9 10.5 0 1 0 87 102 A9 10.5 0 1 0 69 102 Z', 'white'), AP('M71.6 103 A6.4 6.4 0 1 0 84.4 103 A6.4 6.4 0 1 0 71.6 103 Z', 'eye'), AP('M74.8 103 A3.2 3.2 0 1 0 81.2 103 A3.2 3.2 0 1 0 74.8 103 Z', 'ink'), AP('M78.3 100.4 A1.9 1.9 0 1 0 82.10000000000001 100.4 A1.9 1.9 0 1 0 78.3 100.4 Z', 'white'), AP('M68 99 C73 91 83 91 88 99', 'none', stroke: 'ink', sw: 2.4), AP('M113 102 A9 10.5 0 1 0 131 102 A9 10.5 0 1 0 113 102 Z', 'white'), AP('M115.6 103 A6.4 6.4 0 1 0 128.4 103 A6.4 6.4 0 1 0 115.6 103 Z', 'eye'), AP('M118.8 103 A3.2 3.2 0 1 0 125.2 103 A3.2 3.2 0 1 0 118.8 103 Z', 'ink'), AP('M122.3 100.4 A1.9 1.9 0 1 0 126.10000000000001 100.4 A1.9 1.9 0 1 0 122.3 100.4 Z', 'white'), AP('M112 99 C117 91 127 91 132 99', 'none', stroke: 'ink', sw: 2.4)],
  'almond': [AP('M66 102 C72 93 84 93 90 102 C84 110 72 110 66 102 Z', 'white'), AP('M71.6 103 A6.4 6.4 0 1 0 84.4 103 A6.4 6.4 0 1 0 71.6 103 Z', 'eye'), AP('M74.8 103 A3.2 3.2 0 1 0 81.2 103 A3.2 3.2 0 1 0 74.8 103 Z', 'ink'), AP('M78.3 100.4 A1.9 1.9 0 1 0 82.10000000000001 100.4 A1.9 1.9 0 1 0 78.3 100.4 Z', 'white'), AP('M68 99 C73 91 83 91 88 99', 'none', stroke: 'ink', sw: 2.4), AP('M110 102 C116 93 128 93 134 102 C128 110 116 110 110 102 Z', 'white'), AP('M115.6 103 A6.4 6.4 0 1 0 128.4 103 A6.4 6.4 0 1 0 115.6 103 Z', 'eye'), AP('M118.8 103 A3.2 3.2 0 1 0 125.2 103 A3.2 3.2 0 1 0 118.8 103 Z', 'ink'), AP('M122.3 100.4 A1.9 1.9 0 1 0 126.10000000000001 100.4 A1.9 1.9 0 1 0 122.3 100.4 Z', 'white'), AP('M112 99 C117 91 127 91 132 99', 'none', stroke: 'ink', sw: 2.4)],
  'lashes': [AP('M69 102 A9 10.5 0 1 0 87 102 A9 10.5 0 1 0 69 102 Z', 'white'), AP('M71.6 103 A6.4 6.4 0 1 0 84.4 103 A6.4 6.4 0 1 0 71.6 103 Z', 'eye'), AP('M74.8 103 A3.2 3.2 0 1 0 81.2 103 A3.2 3.2 0 1 0 74.8 103 Z', 'ink'), AP('M78.3 100.4 A1.9 1.9 0 1 0 82.10000000000001 100.4 A1.9 1.9 0 1 0 78.3 100.4 Z', 'white'), AP('M70 96 L65 92 M69 100 L64 98', 'none', stroke: 'ink', sw: 2.2), AP('M68 99 C73 91 83 91 88 99', 'none', stroke: 'ink', sw: 2.4), AP('M113 102 A9 10.5 0 1 0 131 102 A9 10.5 0 1 0 113 102 Z', 'white'), AP('M115.6 103 A6.4 6.4 0 1 0 128.4 103 A6.4 6.4 0 1 0 115.6 103 Z', 'eye'), AP('M118.8 103 A3.2 3.2 0 1 0 125.2 103 A3.2 3.2 0 1 0 118.8 103 Z', 'ink'), AP('M122.3 100.4 A1.9 1.9 0 1 0 126.10000000000001 100.4 A1.9 1.9 0 1 0 122.3 100.4 Z', 'white'), AP('M130 96 L135 92 M131 100 L136 98', 'none', stroke: 'ink', sw: 2.2), AP('M112 99 C117 91 127 91 132 99', 'none', stroke: 'ink', sw: 2.4)],
};

const Map<String, List<AP>> avatarPoseEyes = {
  'closed': [AP('M68 104 C73 94 83 94 88 104', 'none', stroke: 'ink', sw: 3.4), AP('M112 104 C117 94 127 94 132 104', 'none', stroke: 'ink', sw: 3.4)],
  'heart': [AP('M78.0 113.9 C67.8 106.2 63.5 100.3 67.0 94.3 C70.3 88.7 76.3 90.1 78.0 94.9 C79.7 90.1 85.7 88.7 89.0 94.3 C92.5 100.3 88.2 106.2 78.0 113.9 Z', '#EA026A'), AP('M122.0 113.9 C111.8 106.2 107.5 100.3 111.0 94.3 C114.3 88.7 120.3 90.1 122.0 94.9 C123.7 90.1 129.7 88.7 133.1 94.3 C136.4 100.3 132.2 106.2 122.0 113.9 Z', '#EA026A')],
  'sun': [AP('M58 90 L94 90 C94 114 64 118 58 90 Z', '#1E1A1C'), AP('M142 90 L106 90 C106 114 136 118 142 90 Z', '#1E1A1C'), AP('M94 92 L106 92', 'none', stroke: '#1E1A1C', sw: 4), AP('M66 96 L74 96', 'none', stroke: '#FFFFFF', sw: 2.4, op: 0.6), AP('M114 96 L122 96', 'none', stroke: '#FFFFFF', sw: 2.4, op: 0.6)],
  'wink': [AP('M68 103 C73 108 83 108 88 103', 'none', stroke: 'ink', sw: 3.4), AP('M113 102 A9 10.5 0 1 0 131 102 A9 10.5 0 1 0 113 102 Z', 'white'), AP('M115.6 103 A6.4 6.4 0 1 0 128.4 103 A6.4 6.4 0 1 0 115.6 103 Z', 'eye'), AP('M118.8 103 A3.2 3.2 0 1 0 125.2 103 A3.2 3.2 0 1 0 118.8 103 Z', 'ink'), AP('M122.3 100.4 A1.9 1.9 0 1 0 126.10000000000001 100.4 A1.9 1.9 0 1 0 122.3 100.4 Z', 'white'), AP('M112 99 C117 91 127 91 132 99', 'none', stroke: 'ink', sw: 2.4)],
  'wide': [AP('M67.5 102 A10.5 12.5 0 1 0 88.5 102 A10.5 12.5 0 1 0 67.5 102 Z', 'white'), AP('M73 102 A5 5 0 1 0 83 102 A5 5 0 1 0 73 102 Z', 'eye'), AP('M75.4 102 A2.6 2.6 0 1 0 80.6 102 A2.6 2.6 0 1 0 75.4 102 Z', 'ink'), AP('M78.4 100 A1.6 1.6 0 1 0 81.6 100 A1.6 1.6 0 1 0 78.4 100 Z', 'white'), AP('M67 98 C73 88 83 88 89 98', 'none', stroke: 'ink', sw: 2.2), AP('M111.5 102 A10.5 12.5 0 1 0 132.5 102 A10.5 12.5 0 1 0 111.5 102 Z', 'white'), AP('M117 102 A5 5 0 1 0 127 102 A5 5 0 1 0 117 102 Z', 'eye'), AP('M119.4 102 A2.6 2.6 0 1 0 124.6 102 A2.6 2.6 0 1 0 119.4 102 Z', 'ink'), AP('M122.4 100 A1.6 1.6 0 1 0 125.6 100 A1.6 1.6 0 1 0 122.4 100 Z', 'white'), AP('M111 98 C117 88 127 88 133 98', 'none', stroke: 'ink', sw: 2.2)],
  'sleepy': [AP('M68 103 C73 108 83 108 88 103', 'none', stroke: 'ink', sw: 3.2), AP('M112 103 C117 108 127 108 132 103', 'none', stroke: 'ink', sw: 3.2)],
};

const Map<String, List<AP>> avatarBrows = {
  'soft': [AP('M67 86 C74 81 82 81 89 85', 'none', stroke: 'hairShade', sw: 3.4), AP('M111 85 C118 81 126 81 133 86', 'none', stroke: 'hairShade', sw: 3.4)],
  'thick': [AP('M66 86 C74 79 84 79 90 84 L90 88 C82 85 74 86 66 90 Z', 'hairShade'), AP('M134 86 C126 79 116 79 110 84 L110 88 C118 85 126 86 134 90 Z', 'hairShade')],
  'straight': [AP('M65 84 L90 83 L90 88 L65 89 Z', 'hairShade'), AP('M135 84 L110 83 L110 88 L135 89 Z', 'hairShade')],
  'arched': [AP('M66 88 C72 78 82 78 90 86', 'none', stroke: 'hairShade', sw: 3), AP('M110 86 C118 78 128 78 134 88', 'none', stroke: 'hairShade', sw: 3)],
};

const Map<String, List<AP>> avatarPoseBrows = {
  'sad': [AP('M66 90 L88 82', 'none', stroke: 'hairShade', sw: 3.4), AP('M134 90 L112 82', 'none', stroke: 'hairShade', sw: 3.4)],
  'angry': [AP('M66 82 L90 90', 'none', stroke: 'hairShade', sw: 4), AP('M134 82 L110 90', 'none', stroke: 'hairShade', sw: 4)],
};

const Map<String, List<AP>> avatarNoses = {
  'button': [AP('M96 116 C96 122 104 122 104 116', 'none', stroke: 'skinShade', sw: 3)],
  'small': [AP('M100 104 L96 118 C98 121 102 121 104 118', 'none', stroke: 'skinShade', sw: 2.6)],
  'line': [AP('M98 106 C96 112 96 116 101 118', 'none', stroke: 'skinShade', sw: 2.6)],
};

const Map<String, List<AP>> avatarMouths = {
  'smile': [AP('M86 130 C92 140 108 140 114 130', 'none', stroke: 'ink', sw: 3.2)],
  'grin': [AP('M82 128 C84 146 116 146 118 128 Z', '#5A1E2E'), AP('M86 129 L114 129 L112 134 L88 134 Z', '#FFFFFF'), AP('M92 141 C96 137 104 137 108 141 C104 144 96 144 92 141 Z', '#FF8FA3')],
  'laugh': [AP('M78 126 C80 152 120 152 122 126 Z', '#5A1E2E'), AP('M82 127 L118 127 L116 133 L84 133 Z', '#FFFFFF'), AP('M88 144 C94 138 106 138 112 144 C106 149 94 149 88 144 Z', '#FF8FA3')],
  'o': [AP('M93 136 A7 9 0 1 0 107 136 A7 9 0 1 0 93 136 Z', '#5A1E2E')],
  'frown': [AP('M88 140 C94 131 106 131 112 140', 'none', stroke: 'ink', sw: 3.2)],
  'flat': [AP('M88 134 L112 134', 'none', stroke: 'ink', sw: 3.2)],
  'kiss': [AP('M96 128 C104 128 106 134 100 136 C106 138 104 144 96 144', 'none', stroke: 'lip', sw: 3.4)],
  'tongue': [AP('M84 128 C88 142 112 142 116 128 Z', '#5A1E2E'), AP('M94 134 C94 150 108 150 108 134 Z', '#FF7F97')],
  'lips': [AP('M86 132 C92 128 97 130 100 131 C103 130 108 128 114 132 C108 140 92 140 86 132 Z', 'lip')],
};

const Map<String, List<AP>> avatarFacialHair = {
  'none': [],
  'stubble': [AP('M58 124 C62 152 84 164 100 164 C116 164 138 152 142 124 C132 142 116 148 100 148 C84 148 68 142 58 124 Z', 'hairShade', op: 0.3)],
  'mustache': [AP('M82 128 C90 120 98 122 100 126 C102 122 110 120 118 128 C110 130 104 130 100 128 C96 130 90 130 82 128 Z', 'hair')],
  'beard': [AP('M52 110 C54 150 80 170 100 170 C120 170 146 150 148 110 C140 130 128 142 114 140 C108 136 92 136 86 140 C72 142 60 130 52 110 Z', 'hair'), AP('M84 128 C92 122 98 124 100 127 C102 124 108 122 116 128 C108 131 92 131 84 128 Z', 'hair')],
  'full': [AP('M46 104 C46 152 76 176 100 176 C124 176 154 152 154 104 C148 126 136 140 118 140 C110 134 90 134 82 140 C64 140 52 126 46 104 Z', 'hair'), AP('M82 128 C90 120 98 122 100 126 C102 122 110 120 118 128 C110 132 90 132 82 128 Z', 'hair')],
  'chevron': [AP('M80 130 C88 120 98 122 100 125 C102 122 112 120 120 130 C112 128 104 129 100 130 C96 129 88 128 80 130 Z', 'hair')],
  'goatee': [AP('M88 140 C90 156 110 156 112 140 C106 146 94 146 88 140 Z', 'hair'), AP('M86 128 C92 123 98 124 100 127 C102 124 108 123 114 128', 'none', stroke: 'hair', sw: 3)],
};

const Map<String, List<AP>> avatarGlasses = {
  'none': [],
  'round': [AP('M63 102 A15 15 0 1 0 93 102 A15 15 0 1 0 63 102 Z', 'none', stroke: 'glasses', sw: 3.2), AP('M107 102 A15 15 0 1 0 137 102 A15 15 0 1 0 107 102 Z', 'none', stroke: 'glasses', sw: 3.2), AP('M93 102 C96 98 104 98 107 102', 'none', stroke: 'glasses', sw: 3)],
  'square': [AP('M62 91 h32 v22 h-32 Z', 'none', stroke: 'glasses', sw: 3.2), AP('M106 91 h32 v22 h-32 Z', 'none', stroke: 'glasses', sw: 3.2), AP('M94 100 L106 100', 'none', stroke: 'glasses', sw: 3)],
  'cateye': [AP('M60 90 L92 94 C94 112 68 116 64 102 Z', 'none', stroke: 'glasses', sw: 3.2), AP('M140 90 L108 94 C106 112 132 116 136 102 Z', 'none', stroke: 'glasses', sw: 3.2), AP('M92 96 L108 96', 'none', stroke: 'glasses', sw: 3)],
};

const Map<String, List<AP>> avatarEarrings = {
  'none': [],
  'studs': [AP('M40.6 118 A3.4 3.4 0 1 0 47.4 118 A3.4 3.4 0 1 0 40.6 118 Z', 'accent'), AP('M152.6 118 A3.4 3.4 0 1 0 159.4 118 A3.4 3.4 0 1 0 152.6 118 Z', 'accent')],
  'hoops': [AP('M36 126 A8 8 0 1 0 52 126 A8 8 0 1 0 36 126 Z', 'none', stroke: 'accent', sw: 2.6), AP('M148 126 A8 8 0 1 0 164 126 A8 8 0 1 0 148 126 Z', 'none', stroke: 'accent', sw: 2.6)],
};

const Map<String, List<AP>> avatarHeadwear = {
  'none': [],
  'beanie': [AP('M40 84 C40 34 70 20 100 20 C130 20 160 34 160 84 Z', 'outfit'), AP('M36 76 h128 v16 h-128 Z', 'outfitShade'), AP('M90 18 A10 10 0 1 0 110 18 A10 10 0 1 0 90 18 Z', 'outfitShade')],
  'cap': [AP('M44 78 C44 38 70 26 100 26 C130 26 156 38 156 78 Z', 'outfit'), AP('M40 78 C70 70 150 70 176 84 C150 90 70 88 40 84 Z', 'outfitShade'), AP('M96 28 A4 4 0 1 0 104 28 A4 4 0 1 0 96 28 Z', 'outfitShade')],
  'bow': [AP('M112 38 C100 16 70 20 76 42 C80 58 102 50 112 44 Z', 'accent'), AP('M112 38 C124 16 154 20 148 42 C144 58 122 50 112 44 Z', 'accent'), AP('M105 41 A7 8 0 1 0 119 41 A7 8 0 1 0 105 41 Z', 'outfitShade')],
  'flowers': [AP('M52.5 44 A5.5 5.5 0 1 0 63.5 44 A5.5 5.5 0 1 0 52.5 44 Z M58.5 50 A5.5 5.5 0 1 0 69.5 50 A5.5 5.5 0 1 0 58.5 50 Z M52.5 56 A5.5 5.5 0 1 0 63.5 56 A5.5 5.5 0 1 0 52.5 56 Z M46.5 50 A5.5 5.5 0 1 0 57.5 50 A5.5 5.5 0 1 0 46.5 50 Z M74.5 30 A5.5 5.5 0 1 0 85.5 30 A5.5 5.5 0 1 0 74.5 30 Z M80.5 36 A5.5 5.5 0 1 0 91.5 36 A5.5 5.5 0 1 0 80.5 36 Z M74.5 42 A5.5 5.5 0 1 0 85.5 42 A5.5 5.5 0 1 0 74.5 42 Z M68.5 36 A5.5 5.5 0 1 0 79.5 36 A5.5 5.5 0 1 0 68.5 36 Z M94.5 26 A5.5 5.5 0 1 0 105.5 26 A5.5 5.5 0 1 0 94.5 26 Z M100.5 32 A5.5 5.5 0 1 0 111.5 32 A5.5 5.5 0 1 0 100.5 32 Z M94.5 38 A5.5 5.5 0 1 0 105.5 38 A5.5 5.5 0 1 0 94.5 38 Z M88.5 32 A5.5 5.5 0 1 0 99.5 32 A5.5 5.5 0 1 0 88.5 32 Z M114.5 30 A5.5 5.5 0 1 0 125.5 30 A5.5 5.5 0 1 0 114.5 30 Z M120.5 36 A5.5 5.5 0 1 0 131.5 36 A5.5 5.5 0 1 0 120.5 36 Z M114.5 42 A5.5 5.5 0 1 0 125.5 42 A5.5 5.5 0 1 0 114.5 42 Z M108.5 36 A5.5 5.5 0 1 0 119.5 36 A5.5 5.5 0 1 0 108.5 36 Z M136.5 44 A5.5 5.5 0 1 0 147.5 44 A5.5 5.5 0 1 0 136.5 44 Z M142.5 50 A5.5 5.5 0 1 0 153.5 50 A5.5 5.5 0 1 0 142.5 50 Z M136.5 56 A5.5 5.5 0 1 0 147.5 56 A5.5 5.5 0 1 0 136.5 56 Z M130.5 50 A5.5 5.5 0 1 0 141.5 50 A5.5 5.5 0 1 0 130.5 50 Z ', '#FFB3CC'), AP('M54 50 A4 4 0 1 0 62 50 A4 4 0 1 0 54 50 Z M76 36 A4 4 0 1 0 84 36 A4 4 0 1 0 76 36 Z M96 32 A4 4 0 1 0 104 32 A4 4 0 1 0 96 32 Z M116 36 A4 4 0 1 0 124 36 A4 4 0 1 0 116 36 Z M138 50 A4 4 0 1 0 146 50 A4 4 0 1 0 138 50 Z ', '#FFD25C')],
};

const Map<String, APose> avatarPoses = {
  'happy': APose(eyes: null, mouth: 'smile', brows: null, extra: [], texts: []),
  'laugh': APose(eyes: 'closed', mouth: 'laugh', brows: null, extra: [], texts: []),
  'wink': APose(eyes: 'wink', mouth: 'tongue', brows: null, extra: [], texts: []),
  'love': APose(eyes: 'heart', mouth: 'grin', brows: null, extra: [AP('M40.0 49.8 C31.6 43.5 28.1 38.6 30.9 33.7 C33.7 29.1 38.6 30.2 40.0 34.1 C41.4 30.2 46.3 29.1 49.1 33.7 C51.9 38.6 48.4 43.5 40.0 49.8 Z', '#EA026A'), AP('M166.0 65.0 C160.0 60.5 157.5 57.0 159.5 53.5 C161.5 50.2 165.0 51.0 166.0 53.8 C167.0 51.0 170.5 50.2 172.5 53.5 C174.5 57.0 172.0 60.5 166.0 65.0 Z', '#FF5C9E'), AP('M28.0 81.6 C23.2 78.0 21.2 75.2 22.8 72.4 C24.4 69.8 27.2 70.4 28.0 72.6 C28.8 70.4 31.6 69.8 33.2 72.4 C34.8 75.2 32.8 78.0 28.0 81.6 Z', '#FF8DBB')], texts: []),
  'cool': APose(eyes: 'sun', mouth: 'smile', brows: null, extra: [], texts: []),
  'wow': APose(eyes: 'wide', mouth: 'o', brows: null, extra: [AP('M118.0 16 h64 a10 10 0 0 1 10 10 v16 a10 10 0 0 1 -10 10 h-42 l-12 12 l2 -12 h-2 a10 10 0 0 1 -10 -10 v-16 a10 10 0 0 1 10 -10 Z', '#FFFFFF', stroke: '#2A0A1A', sw: 2.5)], texts: [AT('OMG', 155, 37, 17, '#EA026A', 'Fredoka')]),
  'sad': APose(eyes: null, mouth: 'frown', brows: 'sad', extra: [AP('M136 110 C132 118 132 124 136 126 C140 124 140 118 136 110 Z', '#8EC5F0')], texts: []),
  'angry': APose(eyes: null, mouth: 'flat', brows: 'angry', extra: [AP('M160 36 l6 -12 l6 12 l-6 -4 Z M172 50 l12 -6 l-4 12 l-2 -6 Z', '#E0354F')], texts: []),
  'kiss': APose(eyes: 'closed', mouth: 'kiss', brows: null, extra: [AP('M146.0 128.4 C138.8 123.0 135.8 118.8 138.2 114.6 C140.6 110.6 144.8 111.6 146.0 115.0 C147.2 111.6 151.4 110.6 153.8 114.6 C156.2 118.8 153.2 123.0 146.0 128.4 Z', '#EA026A')], texts: []),
  'sleepy': APose(eyes: 'sleepy', mouth: 'flat', brows: null, extra: [], texts: [AT('z', 150, 58, 16, '#7B4AE2', 'Fredoka'), AT('Z', 162, 42, 22, '#7B4AE2', 'Fredoka')]),
  'hi': APose(eyes: null, mouth: 'grin', brows: null, extra: [AP('M118.0 16 h64 a10 10 0 0 1 10 10 v16 a10 10 0 0 1 -10 10 h-42 l-12 12 l2 -12 h-2 a10 10 0 0 1 -10 -10 v-16 a10 10 0 0 1 10 -10 Z', '#FFFFFF', stroke: '#2A0A1A', sw: 2.5)], texts: [AT('Hi!', 155, 37, 17, '#EA026A', 'Fredoka')]),
  'lol': APose(eyes: 'closed', mouth: 'laugh', brows: null, extra: [AP('M118.0 16 h64 a10 10 0 0 1 10 10 v16 a10 10 0 0 1 -10 10 h-42 l-12 12 l2 -12 h-2 a10 10 0 0 1 -10 -10 v-16 a10 10 0 0 1 10 -10 Z', '#FFFFFF', stroke: '#2A0A1A', sw: 2.5)], texts: [AT('LOL', 155, 37, 17, '#EA026A', 'Fredoka')]),
  'yay': APose(eyes: 'closed', mouth: 'grin', brows: null, extra: [AP('M34 30 l4 10 l10 2 l-8 6 l2 10 l-8 -6 l-8 6 l2 -10 l-8 -6 l10 -2 Z', '#FFB547'), AP('M160 22 l3 7 l7 1 l-5 4 l1 7 l-6 -4 l-6 4 l1 -7 l-5 -4 l7 -1 Z', '#EA026A'), AP('M20 70 A4 4 0 1 0 28 70 A4 4 0 1 0 20 70 Z', '#8EC5F0'), AP('M172 64 A4 4 0 1 0 180 64 A4 4 0 1 0 172 64 Z', '#A8E6B8')], texts: []),
  'bye': APose(eyes: null, mouth: 'smile', brows: null, extra: [AP('M118.0 16 h64 a10 10 0 0 1 10 10 v16 a10 10 0 0 1 -10 10 h-42 l-12 12 l2 -12 h-2 a10 10 0 0 1 -10 -10 v-16 a10 10 0 0 1 10 -10 Z', '#FFFFFF', stroke: '#2A0A1A', sw: 2.5)], texts: [AT('Bye!', 155, 37, 17, '#EA026A', 'Fredoka')]),
};
