// Patches the platform folders generated by `flutter create` with the
// permissions and ids this app needs. Safe to run more than once.
//
//   dart run tool/setup_platforms.dart
import 'dart:io';

void main() {
  _android();
  _ios();
  stdout.writeln('\nPlatform setup done.');
}

void _android() {
  final template = File('tool/templates/AndroidManifest.xml');
  final target = File('android/app/src/main/AndroidManifest.xml');
  if (!target.existsSync()) {
    stdout.writeln('! android/ not found. Run `flutter create .` first.');
    return;
  }
  if (!template.existsSync()) {
    stdout.writeln('! tool/templates/AndroidManifest.xml is missing.');
    return;
  }
  target.writeAsStringSync(template.readAsStringSync());
  stdout.writeln('✓ AndroidManifest.xml updated');

  // photo_manager needs 21+. google_mobile_ads 9 needs 24.
  for (final name in ['android/app/build.gradle.kts', 'android/app/build.gradle']) {
    final f = File(name);
    if (!f.existsSync()) continue;
    var s = f.readAsStringSync();
    final before = s;
    s = s.replaceAll(
        RegExp(r'minSdk\s*=\s*flutter\.minSdkVersion'), 'minSdk = 24');
    s = s.replaceAll(
        RegExp(r'minSdkVersion\s+flutter\.minSdkVersion'), 'minSdkVersion 24');
    if (s != before) {
      f.writeAsStringSync(s);
      stdout.writeln('✓ $name minSdk set to 24');
    }
  }
}

void _ios() {
  final plist = File('ios/Runner/Info.plist');
  if (!plist.existsSync()) {
    stdout.writeln('- ios/ not found, skipping iOS.');
    return;
  }
  var s = plist.readAsStringSync();
  const entries = <String, String>{
    'NSPhotoLibraryUsageDescription':
        '<string>Enhancify needs access to your photos so you can enhance them.</string>',
    'NSPhotoLibraryAddUsageDescription':
        '<string>Enhancify saves your enhanced photos and videos to your library.</string>',
    'NSCameraUsageDescription':
        '<string>Enhancify uses the camera to take photos to enhance.</string>',
    'NSAppleMusicUsageDescription':
        '<string>Enhancify lets you pick a song to add to your photo.</string>',
    'NSMicrophoneUsageDescription':
        '<string>Enhancify needs the microphone to record videos.</string>',
    'PHPhotoLibraryPreventAutomaticLimitedAccessAlert': '<true/>',
    // Google's TEST AdMob app id. Replace with yours before release.
    'GADApplicationIdentifier':
        '<string>ca-app-pub-3940256099942544~1458002511</string>',
    'LSApplicationQueriesSchemes':
        '<array><string>https</string><string>mailto</string></array>',
    'SKAdNetworkItems':
        '<array><dict><key>SKAdNetworkIdentifier</key><string>cstr6suwn9.skadnetwork</string></dict></array>',
  };
  final buf = StringBuffer();
  entries.forEach((k, v) {
    if (!s.contains('<key>$k</key>')) {
      buf.writeln('\t<key>$k</key>\n\t$v');
    }
  });
  if (buf.isEmpty) {
    stdout.writeln('✓ Info.plist already configured');
    return;
  }
  final idx = s.lastIndexOf('</dict>');
  if (idx < 0) {
    stdout.writeln('! Info.plist looks malformed, skipping.');
    return;
  }
  s = s.substring(0, idx) + buf.toString() + s.substring(idx);
  plist.writeAsStringSync(s);
  stdout.writeln('✓ Info.plist updated');
}
